# Generated by Django 3.1.4 on 2021-03-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notetaking', '0002_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_code',
            field=models.CharField(default='ABCDEF', max_length=6),
            preserve_default=False,
        ),
    ]
