# Generated by Django 3.1.4 on 2021-03-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notetaking', '0003_class_class_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('text', models.CharField(max_length=15000)),
                ('date', models.DateTimeField()),
                ('notetaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notetaking.userprofile')),
                ('which_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notetaking.class')),
            ],
        ),
    ]
