# Generated by Django 3.1.4 on 2021-03-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notetaking', '0006_auto_20210328_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
    ]
