# Generated by Django 3.1.4 on 2021-03-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notetaking', '0007_remove_note_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='school_code',
        ),
    ]
